const DSA_STATUS = {
    ""      : "",
    "REJ_AGE": "Tuổi không phù hợp (từ 20-60)",
    "REJ_INCOME": "Thu nhập dưới 4 triệu đồng",
    "REJ_FINCAP": "Khả năng tài chính không phù hợp",
    "REJ_POLICY": "Không thỏa chính sách cho vay tại EC",
    "NOT_ELIGIBLE": "Cập nhật lần đầu không thành công",
    "FAIL_EKYC": "eKYC thất bại",
    "KYC_RJPOLICY": "Không thỏa chính sách cho vay tại EC",
    "CKYC-WRI01": "Sai tên",
    "CKYC-WRI02": "Sai ngày tháng năm sinh",
    "CKYC-WRI03": "Sai số CMND",
    "CKYC-WRI04": "Sai số CMND",
    "CKYC-WRI05": "Sai số CMND",
    "CKYC-MIS01": "Vượt quá số ký tự cho phép",
    "CKYC-EXP01": "CMND quá hạn",
    "CKYC-WRI06": "CMND sai định dạng, không phải CMND theo quy định (CM quân đội, hộ chiếu, thẻ quân nhân,…)",
    "CKYC-MID01": "Thiếu hình mặt trước/sau CMND, selfie",
    "CKYC-MID02": "Thiếu toàn bộ hình",
    "CKYC-QUD01": "CMND bị mờ",
    "CKYC-QUD02": "Hình selfie bị mờ, không rõ ràng, chói lóa, có vật cản,..",
    "CKYC-WRD01": "Hình chụp KH không hợp lệ (nghiêng mặt, cúi mặt, sử dụng phần mềm chỉnh sửa, khoảng cách chụp quá xa hoặc không phải ảnh chân dung…)",
    "CKYC-WRD03": "Sai thứ tự hình ảnh",
    "CKYC-MM001": "Yêu cầu kiểm lại toàn bộ thông tin KH",
    "ADD-CURR01": "Sai địa chỉ KH",
    "CNTT-PRIM1": "Không liên hệ được KH để xác nhận thông tin",
    "CNTT-RFTCF": "KH không đồng ý xác nhận lại thông tin",
    "CKYC-DOI01": "Sai ngày cấp CMND/CCCD",
    "CKYC-IVLID": "Hình CMND/CCCD vô hiệu (vd mất góc, cắt góc, đục lỗ, CMND photo, in màu…)",
    "CKYC-OTDEV": "Hình CMND/CCCD chụp qua thiết bị khác, không chụp trực tiếp, …",
    "CKYC-PHONE": "Trùng số điện thoại (sdt KH, người thân trùng nhau)",
    "REJ_POLICY, ": "Không thỏa chính sách cho vay tại EC",
    "NOT_SUITABLE_OFFER": "Đề nghị khoản vay không phù hợp",
    "DUPLICATED": "Trùng hồ sơ"
}