const DSA_STATUS = {
    ""      : "",
    "REJ_AGE": "Age (out of range 20-60)",
    "REJ_INCOME": "Income (< 4.5 MVND)",
    "REJ_FINCAP": "Financial capability",
    "REJ_POLICY": "Not meet policy requirement ",
    "NOT_ELIGIBLE": "Fail initial update",
    "FAIL_EKYC": "Fail eKYC",
    "KYC_RJPOLICY": "Not meet requirement ",
    "CKYC-WRI01": "Wrong full name",
    "CKYC-WRI02": "Wrong DOB",
    "CKYC-WRI03": "Wrong ID number (totally)",
    "CKYC-WRI04": "Wrong ID number (1-2 numbers), suspect different ID number",
    "CKYC-WRI05": "Wrong ID number (more than 2 numbers, not totally)",
    "CKYC-MIS01": "Exceeded characters",
    "CKYC-EXP01": "Expired DOI",
    "CKYC-WRI06": "Military ID / Passport / Wrong Format",
    "CKYC-MID01": "Missing selfie photo or NID/PID front side/ back side",
    "CKYC-MID02": "All photos and NID/PID missing",
    "CKYC-QUD01": "Blurred information/ photo in NID/PID ",
    "CKYC-QUD02": "Selfie photo is blurred/ not clearly/ covered",
    "CKYC-WRD01": "Disqualified selfie photo ",
    "CKYC-WRD03": "Wrong order of photos",
    "CKYC-MM001": "Multi Mistakes",
    "ADD-CURR01": "Incorrect current address",
    "CNTT-PRIM1": "Uncontacted primary phone",
    "CNTT-RFTCF": "Refuse to confirm",
    "CKYC-DOI01": "Incorrect DOI",
    "CKYC-IVLID": "Invalid ID/PID",
    "CKYC-OTDEV": "ID taken from other device",
    "CKYC-PHONE": "Phone number duplication",
    "REJ_POLICY, ": "Not meet requirement ",
    "NOT_SUITABLE_OFFER": "Not suitable offer",
    "DUPLICATED": "The application is duplicated"
}