var CRM_API_URL = "https://ec02-api.tel4vn.com";
var translator = {
    'term_confirm' : 'Cam kết thông tin',
    'condition_confirm' : 'Đồng ý điều khoản',
    "Please check this box if you want to proceed." : "Vui lòng chọn",
    'issue_date' : 'Ngày cấp CMND',
    'Please select an item in the list' : 'Vui lòng chọn',
    'Please select an item in the list.' : 'Vui lòng chọn',
    'Please fill out this field' : "Vui lòng chọn / điền",
    'please fill out this field' : "Vui lòng chọn / điền",
    'Please fill out this field.' : "Vui lòng chọn / điền",
    'please fill out this field.' : "Vui lòng chọn / điền",
    "tem_province": "Tỉnh",
    "permanent_address": "Địa Chỉ Thường Trú",
    "submit_img_id_card": "Gửi ảnh CMND/CCCD",
    "submit_img_selfie": "Gửi ảnh chân dung",
    "img_selfie": "Ảnh chân dung (file .pdf)",
    "img_id_card": "Ảnh CMND/CCCD (file .pdf)",
    "employment_type": "Công việc hiện tại của bạn",
    "product_type": "Giấy tờ bạn có thể cung cấp",
    "loan_tenor": "Thời hạn khoản vay",
    "loan_amount": "Giá trị khoản vay",
    "offer_detail": "Chi tiết khoản vay",
    "customer_offer_amount": "Giá trị khoản vay",
    "customer_offer_tenor": "Thời hạn khoản vay",
    "customer_offer_percent": "Gói bảo hiểm",
    "customer_offer_total": "Tổng giá trị",
    "customer_offer_monthly": "Thanh toán hàng tháng",
    "business_date": "Business Date",
    "lending_method": "Phương thức vay",
    "loan_detail": "Thông tin khoản vay",
    "gender": "Giới tính",
    "date_of_birth": "Ngày sinh",
    "identity_card_id": "Chứng minh nhân dân",
    "identity_issue_date": "Ngày cấp",
    "identity_issue_place": "Nơi cấp",
    "issue_place" : "Nơi cấp",
    "identity_number": "Chứng minh nhân dân",
    "identity_issued_on": "Ngày cấp",
    "identity_issued_by": "Nơi cấp",
    "district": "Quận / Huyện",
    "ward": "Phường / Xã",
    "address": "Địa chỉ",
    "permanent_province": "Tỉnh / Thành phố",
    "job_type": "Loại hình công việc",
    "employment_contract": "Loại hình hợp đồng lao động",
    "from": "Từ",
    "to": "Đến",
    "contract_term": "Thời hạn hợp đồng",
    "income_method": "Phương thức nhận lương của bạn",
    "income_frequency": "Tần suất nhận lương thu nhập của bạn",
    "income_receiving_date": "Ngày nhận lương hàng tháng của bạn",
    "monthly_income": "Thu nhập chính sau thuế của bạn",
    "other_income": "Thu nhập khác của bạn",
    "monthly_expense": "Tổng chi tiêu hằng tháng của bạn",
    "profession": "Chức danh công việc của bạn",
    "workplace_name": "Nơi làm việc hiện tại của bạn",
    "workplace_phone": "Số điện thoại nơi bạn đang làm việc",
    "workplace_address": "Địa chỉ chi tiết nơi làm việc",
    "house_type": "Loại hình nhà ở của bạn",
    "married_status": "Tình trạng hôn nhân của bạn",
    "years_of_stay": "Thời gian sinh sống ở địa chỉ hiện tại",
    "bank_account": "Số tài khoản người thụ hưởng",
    "beneficiary_name": "Họ và tên người thụ hưởng",
    "bank_branch_code": "Chi nhánh ngân hàng",
    "bank_area": "Tỉnh / Thành phố",
    "bank_code": "Ngân hàng thụ hưởng",
    "disbursement_method": "Phương thức giải ngân bạn muốn",
    "loan_purpose": "Mục đich vay",
    "other_contact": "Thông tin liên lạc khác",
    "detail_contact": "Chi tiết liên hệ",
    "relation_1": "1. Mối quan hệ với bạn",
    "relation_2": "2. Mối quan hệ với bạn",
    "relation_1_phone_number": "Số điện thoại di động 1",
    "relation_2_phone_number": "Số điện thoại di động 2",
    "relation_1_name": "Họ và tên người thân 1",
    "relation_2_name": "Họ và tên người thân 2",
    "dsa_agent_code": "Mã TSA / DSA",
    "month": "Tháng",
    "date": "Ngày",
    "quarter": "Quý",
    "address2": "Địa chỉ 2",
    "alt_phone_number": "Số Điện Thoại Dự Phòng",
    "country_code": "Mã quốc gia",
    "alternative_phone_number": "Số điện thoại thay thế",
    "prev_status": "Trạng thái cuộc gọi trước đó",
    "app_status": "Trạng thái hợp đồng",
    "customer_name" : "Họ và tên khách hàng",
    "phone_number" : "Số điện thoại khách hàng",
    "tem_address" : "Địa chỉ hiện tại",
    "tem_district" : "Quận / Huyện hiện tại",
    "years_of_stay" : "Thời gian sống tại nơi ở",
    "tem_ward" : "Phường / Xã hiện tại",
    "permanent_district" : "Quận / Huyện thường trú",
    "permanent_ward" :  "Phường / Xã thường trú",
    "workplace_province" : "Tỉnh nơi làm việc",
    "workplace_district": "Quận / Huyện nơi làm việc",
    "workplace_ward" : "Phường / Xã nơi làm việc",
    "3rd Party_duration":	"3rd Party_duration",
    "annual_profit":	"Lợi nhuận hàng năm",
    "annual_revenue":	"Doanh thu hàng năm",
    "business_date":		"Ngày cấp giấy phép đăng kí kinh doanh",
    "business_license_number":"giấy phép đăng kí kinh doanh",
    "customer_name":	"",    "does not Exist":	"Không tồn tại",
    "Duplicated":	"Trùng lặp",
    "identity_card_id":	"Số CMND/CCCD",
    "image_id_card":	"Ảnh CMND/CCCD",
    "image_selfie":	"Ảnh chân dung",
    "invalid":	"Không hợp lệ",
    "Invalid":	"Không hợp lệ",
    "invalid for identity_card_id":	"Không hợp lệ cho số CMND",
    "invalid for phone_number":	"Không hợp lệ cho số điện thoại",
    "invalid for product_type":	"Không hợp lệ cho loại sản phẩm",
    "missing":	"Bị thiếu",
    "Missing":	"Bị thiếu",
    "monthly_profit":	"Lợi nhuận hàng tháng",
    "monthly_revenue":	"Doanh thu hàng tháng",
    "must be after date_of_birth":	"Phải lớn hơn ngày sinh",
    "must be at most 15 years before current":	"Tối thiểu 15 năm tính từ hiện tại",
    "must be in between 54 and 20 years before current":	"",
    "must be in between year 1900 and yesterday":	"Phải từ 1900 đến ngày hôm qua",
    "must be in email format":	"Phải đúng định dạng email",
    "must be in format 'dd-MM-yyyy'":	"Phải là định dạng 'dd-MM-yyyy'",
    "must be in pattern '^0\d{9,10}$'":	"Phải là định dạng '^0\d{9,10}$'",
    "must be in pattern '^(\d{9}|\d{12})$'":	"Phải là định dạng '^(\d{9}|\d{12})$'",
    "must be in pattern '^PID_(\d{9}|\d{12})_0\d{9,10}_\w+\.pdf$', as 'PID_[identity_card_id]_[phone_number]_[partner_code][timestamp(epoch milli)].pdf'":"Phải là định dạng '^PID_(\d{9}|\d{12})_0\d{9,10}_\w+\.pdf$', as 'PID_[identity_card_id]_[phone_number]_[partner_code][timestamp(epoch milli)].pdf'",
    "must be number":	"Phải là số",
    "Must not contain multiple consecutive spaces or (’)":	"Không được chứa nhiều dấu cách liên tiếp hoặc (’)",
    "must not contains character (') at the end or beginning":	"Không được chứa ký tự (') ở cuối hoặc",
    "must not contains multiple consecutive spaces or (')":	"Không được chứa nhiều dấu cách liên tiếp hoặc (')",
    "must only contains Vietnamese characters or character (')":	"Chỉ được chứa các ký tự Tiếng Việt hoặc ký tự (')",
    "not Exist in SFTP":	"Không tồn tại trong SFTP",
    "doc_collecting_list" : "Danh sách chứng từ",
    "doc_collecting_list is empty." : "Danh sách chứng từ trống"
}